[package]
name = "Harvest"
version = "1.0.0"
upgrade_policy = "immutable"

[addresses]
harvest = "0x09d4b8802c2a21d99aed19a11991863ffc9b57122795de493b3a2ade9e7ac81e"
# todo: replace with another address on real deploy
stake_emergency_admin = "0x09d4b8802c2a21d99aed19a11991863ffc9b57122795de493b3a2ade9e7ac81e"

# Test addresses.
treasury = "0x13"
alice = "0x10"
bob = "0x11"
collection_owner = "0x12"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "aptos-release-v1.25"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosToken]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "aptos-release-v1.25"
subdir = "aptos-move/framework/aptos-token"
