[package]
name = 'LiquidswapStakingTests'
version = '1.0.0'

[addresses]
lp_staking_admin = "0xc42b764ca81b34c59d792c2ca875d82f7dfbb5f2905bd3c771cccf0ff20078c5"

[dependencies.Harvest]
local = ".."

[dependencies.Liquidswap]
git = 'https://github.com/pontem-network/liquidswap.git'
rev = 'v0.4.4'