[package]
name = "DGENCoin"
version = "1.0.0"
upgrade_policy = "immutable"

[addresses]
dgen_coin = "0xc42b764ca81b34c59d792c2ca875d82f7dfbb5f2905bd3c771cccf0ff20078c4"

# Test addresses.
alice = "0x10"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "a2a3bf79b68823287f962bded2abfaefc688e71c"
subdir = "aptos-move/framework/aptos-framework"
